import { StyleSheet } from "react-native";
import { themes } from "../../global/themes";

export const styles = StyleSheet.create({
  // container: {
  //   flex: 1,
  //   alignItems: 'center',
  //   //justifyContent: 'center',
  //   backgroundColor: themes.colors.lightRed
  // },
  // header: {
  //   flexDirection: 'row',
  //   justifyContent: 'space-between',
  //   backgroundColor: themes.colors.darkGrey,
  //   //alignItems: 'center',
  //   paddingVertical: 10,
  //   paddingHorizontal: 40,
  //   //paddingBottom: 10,
  //   width: '100%',
  //   marginTop: 60,
  // },
  // buttonHeader: {
  //   width: 40,
  //   height: 40,
  //   borderRadius: 20,
  //   backgroundColor: themes.colors.white,
  //   justifyContent: 'center',
  //   alignItems: 'center',
  //   shadowColor: "#000",
  //   shadowOffset: {
  //       width: 0,
  //       height: 3,
  //   },
  //   shadowOpacity: 0.29,
  //   shadowRadius: 4.65,
  //   elevation: 7,
  // },
  // boxBottom: {
  //   //height:Dimensions.get('window').height/4,
  //   width: '100%',
  //   backgroundColor: 'blue',
  //   alignItems: 'center',
  //   paddingVertical: 10,
  //   //justifyContent: 'flex-end',
  //   //paddingBottom: 115
  // },
  container: {
    flex: 1,
    padding: 16,
    backgroundColor: themes.colors.lightRed,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 16,
    //paddingVertical: 10,
    paddingHorizontal: 30,
    marginTop: 40,
    //width: '100%',
    //backgroundColor: themes.colors.darkGrey,
  },
  buttonHeader: {
    //padding: 10,
    backgroundColor: themes.colors.white,
    width: 40,
    height: 40,
    borderRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: "#000",
     shadowOffset: {
         width: 0,
         height: 3,
     },
     shadowOpacity: 0.29,
     shadowRadius: 4.65,
     elevation: 7,    
  },
  listContainer: {
    paddingBottom: 16,
  },
  instituicaoItem: {
    // marginBottom: 16,
    // padding: 16,
    // backgroundColor: '#f9f9f9',
    // borderRadius: 8,
    // shadowColor: '#000',
    // shadowOffset: { width: 0, height: 2 },
    // shadowOpacity: 0.1,
    // shadowRadius: 4,
    // elevation: 2,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 16,
    marginVertical: 2,
    marginHorizontal: 16,
    backgroundColor: themes.colors.white,
    borderWidth: 2,
    borderColor: themes.colors.darkRed,
    borderRadius: 5,
  },
  instituicaoNome: {
    // fontSize: 16,
    // fontWeight: 'bold',
    // marginBottom: 4,
    flex: 1,
  },
  instituicaoDetalhes: {
    fontSize: 14,
    color: '#555',
  },
  boxBottom: {
    //backgroundColor: 'pink',
    marginTop: 16,
    alignItems: 'center',
  },
  button: {
    backgroundColor: themes.colors.lightGrey,
    paddingVertical: 8,
    //height: '100%',
    paddingHorizontal: 13,
    borderRadius: 5,
    justifyContent: 'center',
    alignItems: 'center',
  },
  buttonText: {
    color: themes.colors.black,
    fontSize: 12,
  },
})